name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add targets
      run: rustup target add ${{ matrix.target }}
    - name: Build
      run: cargo build --verbose --target ${{ matrix.target }}
    - name: Run tests
      run: cargo test --verbose --target ${{ matrix.target }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: target/**
